--- #YAML:1.0
build_requires:
  Test::More: 0.47
conflicts: {}
distribution_type: module
license: perl
name: DateTime-Format-Builder
recommends:
  Test::Pod: 0.95
  Test::Signature: 1.03
requires:
  DateTime: 0.09
  Params::Validate: 0.58
version: 0.6
generated_by: docmaker version 0.89
